# Generated by Django 3.1.3 on 2020-11-23 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_file', models.CharField(max_length=30)),
                ('data_path', models.CharField(blank=True, max_length=30)),
                ('baseline_file', models.CharField(max_length=30)),
                ('baseline_path', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
