# Generated by Django 3.1.3 on 2020-11-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='baseline_file',
            new_name='pat2',
        ),
        migrations.RemoveField(
            model_name='data',
            name='data_file',
        ),
        migrations.AddField(
            model_name='data',
            name='pat1',
            field=models.CharField(default='IX', max_length=30),
        ),
    ]
