# Generated by Django 3.1.3 on 2020-11-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201122_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='baseline_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
