# Generated by Django 3.1.3 on 2020-11-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201122_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='pat1',
            new_name='pattern1',
        ),
        migrations.RemoveField(
            model_name='data',
            name='pat2',
        ),
        migrations.AddField(
            model_name='data',
            name='default_baseline_path',
            field=models.CharField(default='/home/rb/web/MapProfiles/profiles/prof_data/baseline_data/', max_length=200),
        ),
        migrations.AddField(
            model_name='data',
            name='default_data_path',
            field=models.CharField(default='/home/rb/web/MapProfiles/profiles/prof_data/data/', max_length=200),
        ),
        migrations.AddField(
            model_name='data',
            name='pattern2',
            field=models.CharField(default='2020-03', max_length=30),
        ),
        migrations.AlterField(
            model_name='data',
            name='baseline_path',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_path',
            field=models.CharField(max_length=200),
        ),
    ]
