# Generated by Django 3.1.3 on 2020-11-28 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20201125_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='default_baseline_path',
        ),
        migrations.RemoveField(
            model_name='data',
            name='default_data_path',
        ),
    ]
