# Generated by Django 3.1.3 on 2020-12-01 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20201128_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='baseline_path',
        ),
    ]
