# Generated by Django 3.1.3 on 2020-12-01 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_year_month'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Year_Month',
            new_name='Date_meas',
        ),
        migrations.AddField(
            model_name='data',
            name='date_meas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.date_meas'),
        ),
    ]
