# Generated by Django 3.1.3 on 2020-12-07 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20201130_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='data_path',
            new_name='config_path',
        ),
    ]
