# Generated by Django 3.1.4 on 2020-12-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20201206_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='default_config_path',
            field=models.CharField(default='Users\rbas3\\Documents\\web\\MapProfiles\\profiles', max_length=200),
        ),
    ]
