# Generated by Django 3.1.3 on 2020-12-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20201213_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='default_config_path',
            field=models.CharField(default='C', max_length=200),
        ),
    ]
