# Generated by Django 3.1.1 on 2020-12-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_data_data_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_list',
            field=models.TextField(default='files', help_text='list of selected files'),
        ),
    ]
