# Generated by Django 3.1.1 on 2020-12-14 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_auto_20201214_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='data_list',
            new_name='selection',
        ),
    ]
