# Generated by Django 3.1.1 on 2020-12-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20201214_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='selection',
            field=models.TextField(default='files', help_text='list of selected files', max_length=2000),
        ),
    ]
