# Generated by Django 3.1.1 on 2020-12-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_auto_20201214_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='selection',
        ),
    ]
