# Generated by Django 3.1.1 on 2020-12-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_remove_data_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='selection',
            field=models.TextField(default='files', max_length=2000),
        ),
    ]
