# Generated by Django 3.1.1 on 2020-12-15 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_data_selection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_meas',
            field=models.ForeignKey(default='2020-01', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.date_meas'),
        ),
        migrations.AlterField(
            model_name='data',
            name='machine',
            field=models.ForeignKey(default='IX', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.machine'),
        ),
        migrations.AlterField(
            model_name='data',
            name='selection',
            field=models.TextField(default='my selection', max_length=2000),
        ),
    ]
