# Generated by Django 3.1.1 on 2020-12-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_auto_20201215_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'ordering': ['-name']},
        ),
    ]
