# Generated by Django 3.1.3 on 2020-12-17 02:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20201215_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.data')),
            ],
        ),
    ]
