# Generated by Django 3.1.3 on 2020-12-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_datainstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='selection',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
