# Generated by Django 3.1.3 on 2020-12-17 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_auto_20201216_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date_meas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.date_meas'),
        ),
        migrations.AlterField(
            model_name='data',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.machine'),
        ),
    ]
