# Generated by Django 3.1.3 on 2020-12-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_auto_20201216_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='data',
            name='selection',
        ),
        migrations.AddField(
            model_name='data',
            name='data_path',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
        migrations.DeleteModel(
            name='DataInstance',
        ),
    ]
