# Generated by Django 3.1.3 on 2020-12-17 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_remove_data_data_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data_path',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
