# Generated by Django 3.1.3 on 2020-12-17 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_data_data_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='default_data_path',
        ),
    ]
