# Generated by Django 3.1.3 on 2020-12-21 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_remove_data_default_data_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='config_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.configpath'),
        ),
    ]
