# Generated by Django 3.1.3 on 2020-12-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0036_auto_20201221_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configpath',
            name='config_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='data_path',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
